### ISSUE TITLE
Use in .gitlab-ci

### ISSUE THREAD

**Issue by ZwiebelTVDE** [chiticariu/xamarin-android#1]
How do I use this docker image in a .gitlab-ci file? 

Readme file says TBD but it has been months now and it still is TBD

thanks in advance

**Comment by chiticariu** [comment]
Hi @ZwiebelTVDE,

I've updated the Readme file.

Thanks for pointing out that I've forgotten to fill the missing pieces of information.

**Comment by chiticariu** [comment]
In gitlab-ci file I'm using a separate solution that contains the shared project and Android project only, because if you use the solution where is the IOS project, you will have errors.

This is the configuration from the Android project for reference
![image](https://user-images.githubusercontent.com/10170759/84384466-b24e4580-abf6-11ea-9f1e-e967ea86fd15.png)
![image](https://user-images.githubusercontent.com/10170759/84384483-bbd7ad80-abf6-11ea-8142-52b5b6bceb58.png)
![image](https://user-images.githubusercontent.com/10170759/84384522-c8f49c80-abf6-11ea-9419-cb3d528bc8af.png)
